### ISSUE TITLE
[bug] Component - Item 버그 수정 및 리팩토링 작업

### ISSUE THREAD

**Issue by yedol1** [3-14-ketotop/3-14-ketotop#71]
## 버그 내용
- props 에러 핸들링
- 텍스트 길이 제한
- Label 컴포넌트 사용하기
- 스타일 단위 px ⇒ rem으로 수정 ( 1rem = 10px )

## 우려 사항
- 성재님이 제안해주신 파일 분리건은 너무 폴더가 많아지는 것과, 중요도에서 떨어진다고 판단하여 일단 보류하였습니다~!

## 기타
- 수정후 PR 날리겠습니다.

**Comment by ssssssjay** [comment]
파일 분리가, 겹치는 코드 분리시킨다는 말씀이시죠?.?
그거라면 저도 대찬성입니다 ㅎㅎㅎ 바꿔야 할 것들부터 해야할 것 같아요 ㅜㅜ
